name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install requirements
      run: sudo apt install libpcap0.8-dev
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: checking, thats all good
      run: make check
    - name: cleaning binaries
      run: make clean
